#!/bin/bash

# Public domain notice for all NCBI EDirect scripts is located at:
# https://www.ncbi.nlm.nih.gov/books/NBK179288/#chapter6.Public_Domain_Notice

cmd="$1"
shift

useHttps=false
if [ -n "${EDIRECT_HTTPS}" ]
then
  useHttps=true
fi

do_download() {
  if [ "$useHttps" = true ]
  then
    dir="$1"
    msk="$2"
    nquire -lst ftp.ncbi.nlm.nih.gov "$dir" |
    grep "$msk" |
    skip-if-file-exists | tee /dev/stderr |
    nquire -get ftp.ncbi.nlm.nih.gov "$dir" "$msk" > "$msk"
  else
    dir="$1"
    msk="$2"
    nquire -lst ftp.ncbi.nlm.nih.gov "$dir" |
    grep "$msk" |
    skip-if-file-exists | tee /dev/stderr |
    nquire -asp ftp.ncbi.nlm.nih.gov "$dir"
  fi
}

prepare_book_list() {
  echo "<OpenAccessSubset>"
  while IFS=$'\t' read pth titl pblshr dt accn upd
  do
    if [ -n "$accn" ]
    then
      echo "  <Book>"
      echo "    <Accn>$accn</Accn>"
      echo "    <Path>$pth</Path>"
      echo "    <Title>$titl</Title>"
      echo "  </Book>"
    fi
  done
  echo "</OpenAccessSubset>"
}

finish_jtas() {

  tr -s ' ' |
  sed -e 's/^ *//g' -e 's/ *$//g' |
  sort-table -k 1,1f -k 3,3n -k 4,4nr -k 2,2f |
  uniq -i |
  awk -F '\t' '(NR == 1  ||  $1 != prev_key) { if (NR > 1) { print prev_line }; prev_key = $1; prev_line = $0 } END { print prev_line }' |
  cut -f 1,2
}

multi_jtas() {

  tr -s ' ' |
  sed -e 's/^ *//g' -e 's/ *$//g' |
  sort-table -k 1,1f -k 3,3n -k 4,4nr -k 2,2f |
  uniq -i |
  awk -F '\t' '(NR > 1 && $1 == prev_key && $4 == prev_flag) { print } (NR == 1 || $1 != prev_key) { print; prev_key = $1; prev_flag = $4 }' |
  cut -f 1,2 | sort | uniq |
  awk -F '\t' '{ if (NR == 1 || $1 != prev_key) { if (NR > 1) { print saved }; prev_key = $1; saved = $1 "\t" $2 } else { saved = saved " | " $2 } } END { print saved }'
}

case "$cmd" in
  -h | -help | --help | help )
  cat <<EOF
USAGE: $0
       pmc-oa | pmc-bioc | bioconcepts | generif | meshtree | taxnames | serials | journals | oa-list | oa-book | carotene
EOF
    exit 0
    ;;
  pmc-oa | -pmc-oa )
    do_download "pub/pmc/oa_bulk" "xml.tar.gz"
    exit 0
    ;;
  pmc-bioc | -pmc-bioc )
    do_download "pub/wilbur/BioC-PMC" "xml_unicode.tar.gz"
    exit 0
    ;;
  bioconcepts | -bioconcepts )
    do_download "pub/lu/PubTatorCentral" "chemical2pubtatorcentral.gz"
    do_download "pub/lu/PubTatorCentral" "disease2pubtatorcentral.gz"
    do_download "pub/lu/PubTatorCentral" "gene2pubtatorcentral.gz"
    exit 0
    ;;
  generif | -generif | generifs | -generifs )
    do_download "gene/GeneRIF" "generifs_basic.gz"
    do_download "gene/DATA" "gene_info.gz"
    if [ ! -f "geneconv.xml" ]
    then
      gunzip -c gene_info.gz |
      rchive -geneinfo > geneconv.xml
    fi
    if [ ! -f "genename.txt" ]
    then
      cat geneconv.xml |
      xtract -pattern Rec -if Id -and Gene -element Id Gene |
      sort-table -k 1,1n > genename.txt
    fi
    if [ ! -f "genesyns.txt" ]
    then
      cat geneconv.xml |
      xtract -pattern Rec -if Id -and Syns -element Id Syns |
      sort-table -k 1,1n > genesyns.txt
    fi
    exit 0
    ;;
  meshtree | -meshtree )
    if [ ! -f "desc2023.xml" ]
    then
      echo "desc2023.xml"
      nquire -dwn "ftp://nlmpubs.nlm.nih.gov" "online/mesh/MESH_FILES/xmlmesh" "desc2023.gz"
      sleep 1
      if [ ! -f "desc2023.gz" ]
      then
        echo "ERROR - Problem downloading desc2023.gz" >&2
      else
        gunzip -q desc2023.gz
      fi
      sleep 1
      if [ ! -f "desc2023.xml" ] && [ -f "desc2023" ]
      then
        mv desc2023 desc2023.xml
      fi
      if [ ! -f "desc2023.xml" ]
      then
        echo "ERROR - Problem converting desc2023.xml" >&2
      else
        chmod og-wx desc2023.xml
        chmod u-x desc2023.xml
      fi
    fi
    if [ ! -f "pa2023.xml" ]
    then
      echo "pa2023.xml"
      nquire -dwn "ftp://nlmpubs.nlm.nih.gov" "online/mesh/MESH_FILES/xmlmesh" "pa2023.xml"
    fi
    if [ ! -f "qual2023.xml" ]
    then
      echo "qual2023.xml"
      nquire -dwn "ftp://nlmpubs.nlm.nih.gov" "online/mesh/MESH_FILES/xmlmesh" "qual2023.xml"
    fi
    if [ ! -f "supp2023.xml" ]
    then
      echo "supp2023.xml"
      nquire -dwn "ftp://nlmpubs.nlm.nih.gov" "online/mesh/MESH_FILES/xmlmesh" "supp2023.zip"
      unzip -qq supp2023.zip
      rm supp2023.zip
      chmod og-wx supp2023.xml
      chmod u-x supp2023.xml
    fi

    if [ ! -f "meshconv.xml" ]
    then
      cat supp2023.xml |
      xtract -wrp "Set,Rec" -pattern SupplementalRecord \
        -if "SupplementalRecord@SCRClass" -eq 1 \
        -or "SupplementalRecord@SCRClass" -eq 3 \
          -wrp "Code" -element "SupplementalRecord/SupplementalRecordUI" \
          -wrp "Name" -encode "SupplementalRecordName/String" \
          -wrp "Term" -encode "Term/String" > meshtemp.xml
      cat desc2023.xml |
      xtract -wrp "Set,Rec" -pattern DescriptorRecord \
        -wrp "Code" -element "DescriptorRecord/DescriptorUI" \
        -wrp "Name" -first "DescriptorName/String" \
        -wrp "Term" -encode "Term/String" \
        -wrp "Tree" -element "TreeNumberList/TreeNumber" >> meshtemp.xml
      cat meshtemp.xml | xtract -wrp Set -pattern Rec -sort Code |
      transmute -format indent > meshconv.xml
      rm meshtemp.xml
    fi

    if [ ! -f "meshtree.txt" ]
    then
      cat meshconv.xml |
      xtract -pattern Rec -if Tree -element Code -sep "," -element Tree > meshtree.txt
    fi

    if [ ! -f "meshname.txt" ]
    then
      cat meshconv.xml |
      xtract -pattern Rec -if Name -element Code -sep "," -element Name > meshname.txt
    fi

    if [ ! -f "chemconv.xml" ]
    then
      cat supp2023.xml |
      xtract -wrp "Set,Rec" -pattern SupplementalRecord \
        -if "SupplementalRecord@SCRClass" -eq 1 \
          -wrp "Code" -element "SupplementalRecord/SupplementalRecordUI" \
          -wrp "Name" -encode "SupplementalRecordName/String" \
          -wrp "Term" -encode "Term/String" > chemtemp.xml
      cat desc2023.xml |
      xtract -wrp "Set,Rec" -pattern DescriptorRecord \
        -if TreeNumber -starts-with D \
          -wrp "Code" -element "DescriptorRecord/DescriptorUI" \
          -wrp "Name" -first "DescriptorName/String" \
          -wrp "Term" -encode "Term/String" \
          -wrp "Tree" -element "TreeNumberList/TreeNumber" >> chemtemp.xml
      cat chemtemp.xml | xtract -wrp Set -pattern Rec -sort Code |
      transmute -format indent > chemconv.xml
      rm chemtemp.xml
    fi

    if [ ! -f "diszconv.xml" ]
    then
      cat supp2023.xml |
      xtract -wrp "Set,Rec" -pattern SupplementalRecord \
        -if "SupplementalRecord@SCRClass" -eq 3 \
          -wrp "Code" -element "SupplementalRecord/SupplementalRecordUI" \
          -wrp "Name" -encode "SupplementalRecordName/String" \
          -wrp "Term" -encode "Term/String" > disztemp.xml
      cat desc2023.xml |
      xtract -wrp "Set,Rec" -pattern DescriptorRecord \
        -if TreeNumber -starts-with C \
          -wrp "Code" -element "DescriptorRecord/DescriptorUI" \
          -wrp "Name" -first "DescriptorName/String" \
          -wrp "Term" -encode "Term/String" \
          -wrp "Tree" -element "TreeNumberList/TreeNumber" >> disztemp.xml
      cat disztemp.xml | xtract -wrp Set -pattern Rec -sort Code |
      transmute -format indent > diszconv.xml
      rm disztemp.xml
    fi

    exit 0
    ;;
  taxnames | -taxnames | taxonomy | -taxonomy | lineages | -lineages )
    if [ ! -f "new_taxdump.tar.gz" ]
    then
      nquire -asp ftp.ncbi.nlm.nih.gov "pub/taxonomy/new_taxdump" "new_taxdump.tar.gz"
    fi
    if [ ! -f "taxnames.txt" ] && [ -f "new_taxdump.tar.gz" ]
    then
      tar -zxf new_taxdump.tar.gz names.dmp
      cat names.dmp | cut -f 1,3,7 |
      grep -e "scientific name" -e "common name" |
      cut -f 1,2 > taxnames.txt
      rm names.dmp
    fi
    if [ ! -f "lineages.txt" ] && [ -f "new_taxdump.tar.gz" ]
    then
      tar -zxf new_taxdump.tar.gz fullnamelineage.dmp
      cat fullnamelineage.dmp | cut -f 1,3,5 | sort -k 1,1n > lineages.txt
      rm fullnamelineage.dmp
    fi
    exit 0
    ;;
  serials | -serials )
    serfile=.SERFILE
    if [ ! -f "serials.txt" ]
    then
      nquire -get https://ftp.nlm.nih.gov projects/serfilelease |
      sed -ne 's,.* href="\([^/"]*\)".*,\1,p' |
      grep -v marcxml | grep serfilebase | grep 2023 |
      while read fl
      do
        echo "# ${fl}" >> serials.txt
        nquire -get https://ftp.nlm.nih.gov projects/serfilelease "${fl}" > $serfile
        cat "$serfile" |
        xtract -pattern NLMCatalogRecord -def "-" -element NlmUniqueID PublicationInfo/Country >> serials.txt
        cat "$serfile" |
        xtract -pattern DeleteCatalogRecord -block NlmUniqueID -element NlmUniqueID -lbl "-" -deq "\n" >> serials.txt
        rm $serfile
      done
    fi
    if [ -f "serials.txt" ]
    then
      nquire -get https://ftp.nlm.nih.gov projects/serfilelease |
      sed -ne 's,.* href="\([^/"]*\)".*,\1,p' |
      grep -v marcxml | grep -v serfilebase | grep 2023 | sort -f |
      while read fl
      do
        if ! grep -Fq "$fl" serials.txt
        then
          echo "# ${fl}" >> serials.txt
          nquire -get https://ftp.nlm.nih.gov projects/serfilelease "${fl}" > $serfile
          cat "$serfile" |
          xtract -pattern NLMCatalogRecord -def "-" -element NlmUniqueID PublicationInfo/Country >> serials.txt
          cat "$serfile" |
          xtract -pattern DeleteCatalogRecord -block NlmUniqueID -element NlmUniqueID -lbl "-" -deq "\n" >> serials.txt
          rm $serfile
        fi
      done
    fi
    exit 0
    ;;
  journals | -journals )
    if [ ! -f "jourconv.xml" ]
    then
      if [ ! -f "jourcache.xml" ]
      then
        if [ -f "serials.txt" ]
        then
          nquire -ftp ftp.ncbi.nlm.nih.gov pubmed jourcache.xml |
          grep -v DOCTYPE | grep -v ELEMENT | grep -v ATTLIST |
          xtract -transfigure serials.txt \
            -head "<JournalCache>" -tail "</JournalCache>" \
            -pattern Journal -pkg Journal \
              -block "Journal/*" -element "*" \
              -block Journal -wrp Country -translate NlmUniqueID |
          transmute -format > jourcache.xml
        else
          nquire -ftp ftp.ncbi.nlm.nih.gov pubmed jourcache.xml |
          grep -v DOCTYPE | grep -v ELEMENT | grep -v ATTLIST |
          transmute -format > jourcache.xml
        fi
      fi
      cat jourcache.xml |
      xtract -set Set -pattern Journal \
        -if Name -and MedAbbr \
          -NAME Name -ABRV MedAbbr -ACTV ActivityFlag \
          -group Name -pkg Rec \
            -wrp Key -jour Name -wrp Abrv -jour "&ABRV" \
            -wrp Indx -jour "&NAME" -wrp Name -element "&NAME" \
            -wrp Type -lbl "1" -wrp Flag -element "&ACTV" \
          -group MedAbbr -pkg Rec \
            -wrp Key -jour MedAbbr -wrp Abrv -jour "&ABRV" \
            -wrp Indx -jour "&NAME" -wrp Name -element "&NAME" \
            -wrp Type -lbl "2" -wrp Flag -element "&ACTV" \
          -group Alias \
            -block Alias -pkg Rec \
              -wrp Key -jour Alias -wrp Abrv -jour "&ABRV" \
              -wrp Indx -jour "&NAME" -wrp Name -element "&NAME" \
              -wrp Type -lbl "3" -wrp Flag -element "&ACTV" \
          -group Journal -if "&ABRV" -equals "bioRxiv" \
            -block Journal -pkg Rec \
              -wrp Key -lbl "biorxiv.org" -wrp Abrv -jour "&ABRV" \
              -wrp Indx -jour "&NAME" -wrp Name -element "&NAME" \
              -wrp Type -lbl "3" -wrp Flag -element "&ACTV" \
            -block Journal -pkg Rec \
              -wrp Key -lbl "biorxivorg" -wrp Abrv -jour "&ABRV" \
              -wrp Indx -jour "&NAME" -wrp Name -element "&NAME" \
              -wrp Type -lbl "3" -wrp Flag -element "&ACTV" |
      xtract -set Set -pattern Rec \
        -group Rec \
          -block Rec -pkg Rec \
            -wrp Key -lower Key -wrp Abrv -element Abrv \
            -wrp Indx -element Indx -wrp Name -element Name \
            -wrp Type -element Type -wrp Flag -element Flag |
      xtract -set Set -pattern Rec \
        -group Rec \
          -block Rec -pkg Rec \
            -wrp Key -element Key -wrp Abrv -element Abrv \
            -wrp Indx -element Indx -wrp Name -element Name \
            -wrp Type -element Type -wrp Flag -element Flag \
          -block Rec -if Key -starts-with "journal " -pkg Rec \
            -wrp Key -pfx "<Key>the " -element Key -wrp Abrv -element Abrv \
            -wrp Indx -element Indx -wrp Name -element Name \
            -wrp Type -element Type -wrp Flag -element Flag \
          -block Rec -if Key -starts-with "the journal " -pkg Rec \
            -wrp Key -element "Key[5:]" -wrp Abrv -element Abrv \
            -wrp Indx -element Indx -wrp Name -element Name \
            -wrp Type -element Type -wrp Flag -element Flag |
      transmute -format > jourconv.xml
    fi
    if [ ! -f "jourabrv.txt" ]
    then
      cat jourconv.xml | xtract -pattern Rec -element Key Abrv Type Flag | finish_jtas > jourabrv.txt
    fi
    if [ ! -f "jourindx.txt" ]
    then
      cat jourconv.xml | xtract -pattern Rec -element Key Indx Type Flag | finish_jtas > jourindx.txt
    fi
    if [ ! -f "journame.txt" ]
    then
      cat jourconv.xml | xtract -pattern Rec -element Key Name Type Flag | finish_jtas > journame.txt
    fi
    if [ ! -f "joursets.txt" ]
    then
      cat jourconv.xml | xtract -pattern Rec -element Key Name Type Flag | multi_jtas > joursets.txt
    fi
    if [ ! -f "jourmaps.xml" ] && [ -f "jourindx.txt" ]
    then
      cat jourindx.txt | tbl2xml -set JouralMaps -rec Journal Key Indx > jourmaps.xml
    fi
    exit 0
    ;;
  oa-list | -oa-list )
    if [ ! -f "books.xml" ]
    then
      nquire -ftp ftp.ncbi.nlm.nih.gov pub/litarch file_list.txt |
      prepare_book_list > books.xml
    fi
    exit 0
    ;;
  oa-book | -oa-book )
    accn="$1"
    shift
    if [ ! -f "books.xml" ]
    then
      nquire -ftp ftp.ncbi.nlm.nih.gov pub/litarch file_list.txt |
      prepare_book_list > books.xml
    fi
    cat books.xml |
    xtract -pattern Book -if Accn -equals "$accn" -element Path |
    while read pth
    do
      if [ ! -f "$pth" ]
      then
        nquire -dwn ftp.ncbi.nlm.nih.gov "pub/litarch" "$pth"
      fi
    done
    exit 0
    ;;
  carotene | -carotene )
    if [ ! -f "carotene.xml" ]
    then
      nquire -asp ftp.ncbi.nlm.nih.gov "entrez/entrezdirect/samples" "carotene.xml.zip"
      unzip -qq carotene.xml.zip
      rm carotene.xml.zip
    fi
    exit 0
    ;;
  natural-earth | -natural-earth )
    curl -Ls -O "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip"
    curl -Ls -O "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_disputed_areas.zip"
    curl -Ls -O "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces.zip"
    curl -Ls -O "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_geography_marine_polys.zip"
    curl -Ls -O "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_lakes.zip"
    curl -Ls -O "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_minor_islands.zip"
    curl -Ls -O "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_reefs.zip"
    curl -Ls -O "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_rivers_lake_centerlines.zip"
    exit 0
    ;;
  * )
    echo "ERROR - Unrecognized command '$cmd'" >&2
    ;;
esac
